version: "3"

dotenv: [".env"]
silent: true

tasks:
  app:
    -  turbo run dev --scope="smartevm-webapp"

  # Smart contract commands
  node:
    - bun run --cwd "hardhat" node

  # Hasura backend commands  
  console:
    cmds:
      - hasura console --project apps/hasura 

  boot:
    cmds:
      - docker-compose up -d --build database
      - sleep 10
      - docker-compose up -d --build hasura
      - echo "Waiting 30s for postgres and hasura to start ..."
      - sleep 30
      - task migrate

  reboot:
    cmds:
      - task down
      - task boot

  seed:
    cmds:
      - hasura seeds apply --project apps/hasura 

  up:
    cmds:
      - docker-compose up -d --build

  down:
    cmds:
      - docker-compose down -v --remove-orphans

  migrate:
    cmds:
      - hasura migrate apply --project apps/hasura 
      - hasura metadata apply --project apps/hasura 

  reload:
    cmds:
      - task down
      - docker-compose up -d postgres
      - sleep 5
      - docker-compose up -d --build
      - docker-compose logs -f hasura
