revoke delete on table "public"."auction_details" from "anon";

revoke insert on table "public"."auction_details" from "anon";

revoke references on table "public"."auction_details" from "anon";

revoke select on table "public"."auction_details" from "anon";

revoke trigger on table "public"."auction_details" from "anon";

revoke truncate on table "public"."auction_details" from "anon";

revoke update on table "public"."auction_details" from "anon";

revoke delete on table "public"."auction_details" from "authenticated";

revoke insert on table "public"."auction_details" from "authenticated";

revoke references on table "public"."auction_details" from "authenticated";

revoke select on table "public"."auction_details" from "authenticated";

revoke trigger on table "public"."auction_details" from "authenticated";

revoke truncate on table "public"."auction_details" from "authenticated";

revoke update on table "public"."auction_details" from "authenticated";

revoke delete on table "public"."auction_details" from "service_role";

revoke insert on table "public"."auction_details" from "service_role";

revoke references on table "public"."auction_details" from "service_role";

revoke select on table "public"."auction_details" from "service_role";

revoke trigger on table "public"."auction_details" from "service_role";

revoke truncate on table "public"."auction_details" from "service_role";

revoke update on table "public"."auction_details" from "service_role";

revoke delete on table "public"."pre_sale" from "anon";

revoke insert on table "public"."pre_sale" from "anon";

revoke references on table "public"."pre_sale" from "anon";

revoke select on table "public"."pre_sale" from "anon";

revoke trigger on table "public"."pre_sale" from "anon";

revoke truncate on table "public"."pre_sale" from "anon";

revoke update on table "public"."pre_sale" from "anon";

revoke delete on table "public"."pre_sale" from "authenticated";

revoke insert on table "public"."pre_sale" from "authenticated";

revoke references on table "public"."pre_sale" from "authenticated";

revoke select on table "public"."pre_sale" from "authenticated";

revoke trigger on table "public"."pre_sale" from "authenticated";

revoke truncate on table "public"."pre_sale" from "authenticated";

revoke update on table "public"."pre_sale" from "authenticated";

revoke delete on table "public"."pre_sale" from "service_role";

revoke insert on table "public"."pre_sale" from "service_role";

revoke references on table "public"."pre_sale" from "service_role";

revoke select on table "public"."pre_sale" from "service_role";

revoke trigger on table "public"."pre_sale" from "service_role";

revoke truncate on table "public"."pre_sale" from "service_role";

revoke update on table "public"."pre_sale" from "service_role";

alter table "public"."pre_sale" drop constraint "pre_sale_address_key";

alter table "public"."auction_details" drop constraint "auction_details_pkey";

alter table "public"."pre_sale" drop constraint "pre-sale_pkey";

drop index if exists "public"."auction_details_pkey";

drop index if exists "public"."pre-sale_pkey";

drop index if exists "public"."pre_sale_address_key";

drop table "public"."auction_details";

drop table "public"."pre_sale";

create table "public"."auctions" (
    "created_at" timestamp(6) with time zone not null default CURRENT_TIMESTAMP,
    "exact_order_id" bigint not null,
    "symbol_auctioning_token" text,
    "symbol_bidding_token" text,
    "address_auctioning_token" text,
    "address_bidding_token" text,
    "decimals_auctioning_token" smallint,
    "decimals_bidding_token" smallint,
    "end_time_timestamp" timestamp(6) without time zone,
    "order_cancellation_end_date" timestamp(6) without time zone,
    "starting_time_stamp" timestamp(6) without time zone,
    "minimum_bidding_amount_per_order" bigint,
    "min_funding_threshold" bigint,
    "allow_list_manager" text,
    "allow_list_signer" text,
    "current_volume" integer,
    "current_clearing_order_sell_amount" bigint,
    "current_clearing_order_buy_amount" bigint,
    "current_clearing_price" integer,
    "current_bidding_amount" bigint,
    "is_atomic_closure_allowed" boolean,
    "is_private_auction" boolean,
    "interest_score" integer,
    "usd_amount_traded" integer,
    "chain_id" bigint not null
);


create table "public"."indexer" (
    "id" bigint generated by default as identity not null,
    "last_indexed_block" text not null
);


create table "public"."presale" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" bigint,
    "account" text,
    "address" text,
    "signature" text
);


CREATE UNIQUE INDEX indexer_pkey ON public.indexer USING btree (id);

CREATE UNIQUE INDEX auction_details_pkey ON public.auctions USING btree (exact_order_id, chain_id);

CREATE UNIQUE INDEX "pre-sale_pkey" ON public.presale USING btree (id);

CREATE UNIQUE INDEX pre_sale_address_key ON public.presale USING btree (address);

alter table "public"."auctions" add constraint "auction_details_pkey" PRIMARY KEY using index "auction_details_pkey";

alter table "public"."indexer" add constraint "indexer_pkey" PRIMARY KEY using index "indexer_pkey";

alter table "public"."presale" add constraint "pre-sale_pkey" PRIMARY KEY using index "pre-sale_pkey";

alter table "public"."presale" add constraint "pre_sale_address_key" UNIQUE using index "pre_sale_address_key";

grant delete on table "public"."auctions" to "anon";

grant insert on table "public"."auctions" to "anon";

grant references on table "public"."auctions" to "anon";

grant select on table "public"."auctions" to "anon";

grant trigger on table "public"."auctions" to "anon";

grant truncate on table "public"."auctions" to "anon";

grant update on table "public"."auctions" to "anon";

grant delete on table "public"."auctions" to "authenticated";

grant insert on table "public"."auctions" to "authenticated";

grant references on table "public"."auctions" to "authenticated";

grant select on table "public"."auctions" to "authenticated";

grant trigger on table "public"."auctions" to "authenticated";

grant truncate on table "public"."auctions" to "authenticated";

grant update on table "public"."auctions" to "authenticated";

grant delete on table "public"."auctions" to "service_role";

grant insert on table "public"."auctions" to "service_role";

grant references on table "public"."auctions" to "service_role";

grant select on table "public"."auctions" to "service_role";

grant trigger on table "public"."auctions" to "service_role";

grant truncate on table "public"."auctions" to "service_role";

grant update on table "public"."auctions" to "service_role";

grant delete on table "public"."indexer" to "anon";

grant insert on table "public"."indexer" to "anon";

grant references on table "public"."indexer" to "anon";

grant select on table "public"."indexer" to "anon";

grant trigger on table "public"."indexer" to "anon";

grant truncate on table "public"."indexer" to "anon";

grant update on table "public"."indexer" to "anon";

grant delete on table "public"."indexer" to "authenticated";

grant insert on table "public"."indexer" to "authenticated";

grant references on table "public"."indexer" to "authenticated";

grant select on table "public"."indexer" to "authenticated";

grant trigger on table "public"."indexer" to "authenticated";

grant truncate on table "public"."indexer" to "authenticated";

grant update on table "public"."indexer" to "authenticated";

grant delete on table "public"."indexer" to "service_role";

grant insert on table "public"."indexer" to "service_role";

grant references on table "public"."indexer" to "service_role";

grant select on table "public"."indexer" to "service_role";

grant trigger on table "public"."indexer" to "service_role";

grant truncate on table "public"."indexer" to "service_role";

grant update on table "public"."indexer" to "service_role";

grant delete on table "public"."presale" to "anon";

grant insert on table "public"."presale" to "anon";

grant references on table "public"."presale" to "anon";

grant select on table "public"."presale" to "anon";

grant trigger on table "public"."presale" to "anon";

grant truncate on table "public"."presale" to "anon";

grant update on table "public"."presale" to "anon";

grant delete on table "public"."presale" to "authenticated";

grant insert on table "public"."presale" to "authenticated";

grant references on table "public"."presale" to "authenticated";

grant select on table "public"."presale" to "authenticated";

grant trigger on table "public"."presale" to "authenticated";

grant truncate on table "public"."presale" to "authenticated";

grant update on table "public"."presale" to "authenticated";

grant delete on table "public"."presale" to "service_role";

grant insert on table "public"."presale" to "service_role";

grant references on table "public"."presale" to "service_role";

grant select on table "public"."presale" to "service_role";

grant trigger on table "public"."presale" to "service_role";

grant truncate on table "public"."presale" to "service_role";

grant update on table "public"."presale" to "service_role";


