/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NVD6hHq7Sur
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function VideoStrip() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-2xl font-bold">Video Strip</h2>
        <Link href="#" className="text-primary hover:underline" prefetch={false}>
          View All
        </Link>
      </div>
      <div className="relative">
        <div className="overflow-x-auto scrollbar-hide">
          <div className="flex gap-4">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((item) => (
              <div key={item} className="flex-shrink-0 w-40 sm:w-48 md:w-56 lg:w-64 relative group">
                <img
                  src="/placeholder.svg"
                  alt={`Video ${item}`}
                  width={360}
                  height={240}
                  className="rounded-lg object-cover"
                />
                <div className="absolute inset-0 bg-black/50 rounded-lg flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button variant="ghost" size="icon" className="text-white hover:bg-white/20 rounded-full">
                    <PlayIcon className="w-8 h-8" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="absolute top-0 right-0 bottom-0 w-12 bg-gradient-to-l from-white dark:from-gray-950 pointer-events-none" />
      </div>
    </div>
  )
}

function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}
