import { ArrowRightIcon } from 'lucide-react'
import { Card } from '../ui/card'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wu0QVsW0LBh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function SolutionLandingPage({ content }: SolutionLandingPageProps) {
  return (
    <main className="py-24 sm:py-32">
      <div className="px-6 mx-auto max-w-7xl lg:px-8">
        <div className="sm:text-center">
          <h2 className="text-lg font-semibold leading-8">
            {content.mainHeading}
          </h2>
          <p className="mt-2 font-bold heading">{content.subHeading}</p>
          <p className="max-w-2xl mx-auto mt-6 text-lg leading-8">
            {content.description}
          </p>
        </div>
        <div className="flex flex-col mt-20 lg:flex-row lg:items-start">
          {content.features.map((feature, index) => (
            <Card key={index} className="lg:mr-8 lg:w-1/2">
              <div className="relative w-full mx-auto shadow-xl rounded-3xl ring-1 ring-gray-900/5 sm:max-w-md sm:rounded-xl lg:max-w-none lg:rounded-xl">
                <div className="px-6 pt-12 text-center pb-14 lg:px-8 lg:pb-20 lg:pt-16">
                  <div className="flex items-center justify-center w-12 h-12 mx-auto bg-indigo-600 rounded-full">
                    <feature.icon className="w-6 h-6" />
                  </div>
                  <h3 className="mt-8 text-2xl font-semibold tracking-tight">
                    {feature.title}
                  </h3>
                  <p className="mt-4 text-base leading-7">
                    {feature.description}
                  </p>
                </div>
              </div>
            </Card>
          ))}
        </div>
        <div className="mt-20">
          <div className="max-w-2xl mx-auto lg:max-w-none">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              {content.business.heading}
            </h2>
            <p className="mt-6 text-lg leading-8">
              {content.business.description}
            </p>
          </div>
          <div className="flex flex-col max-w-2xl gap-8 mx-auto mt-10 lg:mx-0 lg:max-w-none lg:flex-row lg:items-start">
            {content.advantages.map((advantage, index) => (
              <div key={index} className="flex-auto">
                <div className="flex items-center">
                  <advantage.icon className="flex-none w-12 h-12" />
                  <div className="ml-4 text-xl font-semibold leading-8 tracking-tight">
                    {advantage.title}
                  </div>
                </div>
                <p className="mt-1 text-gray-600">{advantage.description}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col p-12 mt-32 text-white bg-gray-900 rounded-3xl lg:flex-row lg:items-center lg:p-24">
          <div className="flex-1 mb-10 lg:mb-0">
            <h3 className="text-3xl font-semibold">
              {content.callToAction.heading}
            </h3>
            <p className="mt-4 text-lg">{content.callToAction.description}</p>
          </div>
          <div className="flex-none lg:ml-10">
            <a
              className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700"
              href={content.callToAction.buttonHref}
            >
              {content.callToAction.buttonLabel}
              <ArrowRightIcon className="w-5 h-5 ml-3" />
            </a>
          </div>
        </div>
      </div>
    </main>
  )
}
interface Feature {
  title: string
  description: string
  icon: React.ElementType
}

interface BusinessInfo {
  heading: string
  description: string
}

interface Advantage extends Feature {}

interface CallToAction {
  heading: string
  description: string
  buttonLabel: string
  buttonHref: string
}

interface SolutionLandingPageProps {
  content: SolutionLandingPageContent
}

export interface SolutionLandingPageContent {
  mainHeading: string
  subHeading: string
  description: string
  features: Feature[]
  business: BusinessInfo
  advantages: Advantage[]
  callToAction: CallToAction
}
